#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/ephemeral.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-controller
  namespace: {{ .Release.Namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: discovery
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: discovery
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: network-controller
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: network-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: network-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: discovery
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - '*'
  - apiGroups:
      - 'mpc.bosch.com'
    resources:
      - networks
    verbs:
      - '*'
  - apiGroups:
      - 'networking.istio.io'
    resources:
      - gateways
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: network-controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-serving
  namespace: {{ .Release.Namespace }}
{{- if .Values.ephemeral.image.pullSecrets }}
imagePullSecrets:
  {{- range .Values.ephemeral.image.pullSecrets }}
  - name: {{ . }}
  {{- end}}
{{- end}}
