/*
 * Copyright (c) 2021 - for information on the respective copyright owner
 * see the NOTICE file and/or the repository https://github.com/carbynestack/ephemeral.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package io.carbynestack.ephemeral.client;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Value;

/** Input parameters to an Ephemeral function invocation. */
@Value
@Builder
public class Activation {

  /** Identifiers of Amphora secrets that are provided to MPC programs as input. */
  @Builder.Default String[] amphoraParams = new String[0];

  /**
   * Secret shares of parameters that are directly provided.
   *
   * <p>This is currently not supported by the clients provided by this library.
   */
  String[] secretParams = new String[0];

  /**
   * Tag filters of Used Secrets
   *
   * <p>Will be joined via AND's
   */
  @Builder.Default String[] tagFilterParams = new String[0];

  /**
   * The UUID used to correlate function invocations among Carbyne Stack Virtual Cloud Providers.
   * Must be identical for all Ephemeral endpoints.
   */
  String gameId;

  /** The MPC source code that should be invoked. */
  String code;

  /**
   * The type of output generated by the MPC function.
   *
   * <p>Currently only functions that create Amphora objects and return the associated identifiers
   * are supported by the clients provided by this library.
   */
  @JsonProperty OutputConfig output = OutputConfig.AMPHORA_SECRET;
}
