#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/ephemeral.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Build and test artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  test-java:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ephemeral-java-client
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setting up Github Package Repository as Maven Repository
        uses: s4u/maven-settings-action@v2
        with:
          githubServer: false
          servers: |
            [{
              "id": "github",
              "username": "cs-minion",
              "password": "&#103;&#104;&#112;&#95;cUbDuVYAtFgin3nB8cvTjZ3NZTEvLg4Vfhjf"
            }]
      - name: Build with Maven
        run: mvn install -Dskip.tests --batch-mode --update-snapshots --no-transfer-progress
      - name: Run Tests
        run: mvn verify --activate-profiles coverage --batch-mode --no-transfer-progress
      - name: Collect Jacoco reports
        run: echo ::set-output name=reports::$(find . -regex '.*/target/site/jacoco/jacoco.xml' | tr '\n' ',' | sed 's/.$//')
        id: jacoco
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.jacoco.outputs.reports }}
          name: codecov
  test-go:
    runs-on: ubuntu-20.04
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      REGISTRY: ghcr.io
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Setup Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Perform Tests
        run: |
          go test ./... -coverprofile coverage.txt.tmp && cat coverage.txt.tmp | grep -Ev "fake|helper" > coverage.txt
      - name: Publishing Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov
