#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/ephemeral.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Publish Service Chart
on:
  push:
    tags:
      - "chart-v[0-9]+.[0-9]+.[0-9]+"
env:
  REGISTRY: ghcr.io
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version
        run: echo "VERSION=${GITHUB_REF#refs/*/chart-v}" >> $GITHUB_ENV
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Helm Chart
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: ephemeral
          repository: carbynestack
          tag: ${{ env.VERSION }}
          path: charts/ephemeral
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
